// prettier-ignore
const p = {
  bg           : "#24283b",
  bg_dark      : "#1f2335",
  fg           : "#c0caf5",
  fg_dark      : "#a9b1d6",
  fg_gutter    : "#3b4261",
  comment      : "#565f89",
  blue         : "#7aa2f7",
  cyan         : "#7dcfff",
  blue1        : "#2ac3de",
  blue2        : "#0db9d7",
  blue5        : "#89ddff",
  blue6        : "#B4F9F8",
  magenta      : "#bb9af7",
  purple       : "#9d7cd8",
  orange       : "#ff9e64",
  yellow       : "#e0af68",
  green        : "#9ece6a",
  green1       : "#73daca",
  teal         : "#1abc9c",
  red          : "#f7768e",
  red1         : "#db4b4b",
}

// prettier-ignore
export default {
  bg              : p.bg,
  paper_bg        : p.bg_dark,
  fg              : p.fg,
  fg_gutter       : p.fg_gutter,
  success         : p.green,
  tab_hover_bg    : p.bg_dark,
  // TS
  comment         : p.comment,
  constant        : p.orange,
  danger          : p.red1,
  field           : p.green1,
  function        : p.blue,
  keyword         : p.purple,
  keywordFunction : p.magenta,
  label           : p.blue,
  note            : p.blue2,
  operator        : p.blue5,
  parameter       : p.yellow,
  preproc         : p.cyan,
  property        : p.green1,
  punctDelimiter  : p.blue5,
  punctBracket    : p.fg_dark,
  string          : p.green,
  stringEscape    : p.magenta,
  stringRegex     : p.blue6,
  symbol          : p.magenta,
  textReference   : p.teal,
  type            : p.blue1,
  variableBuiltin : p.red,
  warning         : p.yellow,
};
